server:
  port: 8084
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 911368169umid
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    show-sql: true
  mvc:
    servlet:
      path: /api/curierMobile
  application:
    name: COURIERMOBILE
  servlet:
    multipart:
      max-file-size: 10MB
debug: true


