server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 911368169umid
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    servlet:
      path: /api/admin
  servlet:
    multipart:
      max-file-size: 5MB
  application:
    name: ADMIN
debug: true
