server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 250407
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fast_food
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    servlet:
      path: /api
debug: true
