server:
  port: 8089
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    TODO: change eureka parameters to true
spring:
  datasource:
    username: postgres
    password: 911368169umid
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: clientService
  sql:
    init:
      mode: NEVER
debug: true
